dependencies:
  - python=3.11
  - sqlite
  - pandas
  - matplotlib
  - beautifulsoup4
  - scrapy
  - scholarly
  - memory_profiler
  - httpx=0.27.2
  - openpyxl
  - requests  # Extra space removed
  - tqdm
  - pip  # Ensure pip itself is installed within the environment
  - pip:
    - fake_useragent
    - googletrans==4.0.0-rc1
