name: SmallScrapper
dependencies:
  - python=3.11
  - sqlite
  - pandas
  - matplotlib
  - beautifulsoup4
  - scrapy
  - memory_profiler
  - httpx<0.24  # Ensuring compatibility with scholarly
  - openpyxl
  - requests
  - tqdm
  - pip
  - pip:
      - scholarly
      - fake_useragent
      - httpcore[http2]